@startuml
start
:Flush RX buffer;
:TX handshake;

while (Handshake RX?) is (no)
  :sleep;
endwhile (yes)

:Consume handshake;

:Initialize HW;


repeat
  :Pull RC RX data;
  :Write RC RX data;
  :Read IMU data;
  :Write IMU data;

  while (Servo data available?) is (no)
    :sleep;
  endwhile (yes)
  :read servo data;
  :write data to servos;
repeat while
@enduml